/// <reference types='@types/emscripten' />

// TypeScript bindings for emscripten-generated code.  Automatically generated at compile time.
interface WasmModule {
  _openmpt_get_library_version(): number;
  __ZN7openmpt19get_library_versionEv(): number;
  _openmpt_get_core_version(): number;
  __ZN7openmpt16get_core_versionEv(): number;
  _openmpt_free_string(_0: number): void;
  _free(_0: number): void;
  _openmpt_get_string(_0: number): number;
  __ZN7openmpt6string3getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number): void;
  _openmpt_get_supported_extensions(): number;
  _openmpt_is_extension_supported(_0: number): number;
  _openmpt_log_func_default(_0: number, _1: number): void;
  _openmpt_log_func_silent(_0: number, _1: number): void;
  _openmpt_error_is_transient(_0: number): number;
  _openmpt_error_string(_0: number): number;
  _openmpt_error_func_default(_0: number, _1: number): number;
  _openmpt_error_func_log(_0: number, _1: number): number;
  _openmpt_error_func_store(_0: number, _1: number): number;
  _openmpt_error_func_ignore(_0: number, _1: number): number;
  _openmpt_error_func_errno(_0: number, _1: number): number;
  _openmpt_error_func_errno_userdata(_0: number): number;
  _openmpt_could_open_probability(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_could_open_probability2(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number): number;
  _openmpt_could_open_propability(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_probe_file_header_get_recommended_size(): number;
  _openmpt_probe_file_header(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number, _9: number, _10: number, _11: number): number;
  _openmpt_probe_file_header_without_filesize(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number, _9: number): number;
  _openmpt_probe_file_header_from_stream(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number, _9: number): number;
  _openmpt_module_create(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_create2(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number): number;
  _openmpt_module_create_from_memory(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_create_from_memory2(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number): number;
  _openmpt_module_destroy(_0: number): void;
  _openmpt_module_set_log_func(_0: number, _1: number, _2: number): void;
  _openmpt_module_set_error_func(_0: number, _1: number, _2: number): void;
  _openmpt_module_error_get_last(_0: number): number;
  _openmpt_module_error_get_last_message(_0: number): number;
  _openmpt_module_error_set_last(_0: number, _1: number): void;
  _openmpt_module_error_clear(_0: number): void;
  _openmpt_module_select_subsong(_0: number, _1: number): number;
  _openmpt_module_get_selected_subsong(_0: number): number;
  _openmpt_module_set_repeat_count(_0: number, _1: number): number;
  _openmpt_module_get_repeat_count(_0: number): number;
  _openmpt_module_get_duration_seconds(_0: number): number;
  _openmpt_module_set_position_seconds(_0: number, _1: number): number;
  _openmpt_module_get_position_seconds(_0: number): number;
  _openmpt_module_set_position_order_row(_0: number, _1: number, _2: number): number;
  _openmpt_module_get_render_param(_0: number, _1: number, _2: number): number;
  _openmpt_module_set_render_param(_0: number, _1: number, _2: number): number;
  _openmpt_module_read_mono(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_read_stereo(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_read_quad(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): number;
  _openmpt_module_read_float_mono(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_read_float_stereo(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_read_float_quad(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): number;
  _openmpt_module_read_interleaved_stereo(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_read_interleaved_quad(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_read_interleaved_float_stereo(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_read_interleaved_float_quad(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_get_metadata_keys(_0: number): number;
  _openmpt_module_get_metadata(_0: number, _1: number): number;
  _openmpt_module_get_current_estimated_bpm(_0: number): number;
  _openmpt_module_get_current_speed(_0: number): number;
  _openmpt_module_get_current_tempo(_0: number): number;
  _openmpt_module_get_current_tempo2(_0: number): number;
  _openmpt_module_get_current_order(_0: number): number;
  _openmpt_module_get_current_pattern(_0: number): number;
  _openmpt_module_get_current_row(_0: number): number;
  _openmpt_module_get_current_playing_channels(_0: number): number;
  _openmpt_module_get_current_channel_vu_mono(_0: number, _1: number): number;
  _openmpt_module_get_current_channel_vu_left(_0: number, _1: number): number;
  _openmpt_module_get_current_channel_vu_right(_0: number, _1: number): number;
  _openmpt_module_get_current_channel_vu_rear_left(_0: number, _1: number): number;
  _openmpt_module_get_current_channel_vu_rear_right(_0: number, _1: number): number;
  _openmpt_module_get_num_subsongs(_0: number): number;
  _openmpt_module_get_num_channels(_0: number): number;
  _openmpt_module_get_num_orders(_0: number): number;
  _openmpt_module_get_num_patterns(_0: number): number;
  _openmpt_module_get_num_instruments(_0: number): number;
  _openmpt_module_get_num_samples(_0: number): number;
  _openmpt_module_get_subsong_name(_0: number, _1: number): number;
  _openmpt_module_get_channel_name(_0: number, _1: number): number;
  _openmpt_module_get_order_name(_0: number, _1: number): number;
  _openmpt_module_get_pattern_name(_0: number, _1: number): number;
  _openmpt_module_get_instrument_name(_0: number, _1: number): number;
  _openmpt_module_get_sample_name(_0: number, _1: number): number;
  _openmpt_module_get_order_pattern(_0: number, _1: number): number;
  _openmpt_module_get_pattern_num_rows(_0: number, _1: number): number;
  _openmpt_module_get_pattern_row_channel_command(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_format_pattern_row_channel_command(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_highlight_pattern_row_channel_command(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  _openmpt_module_format_pattern_row_channel(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): number;
  _openmpt_module_highlight_pattern_row_channel(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): number;
  _openmpt_module_get_ctls(_0: number): number;
  _openmpt_module_ctl_get(_0: number, _1: number): number;
  _openmpt_module_ctl_get_boolean(_0: number, _1: number): number;
  _openmpt_module_ctl_get_integer(_0: number, _1: number): number;
  _openmpt_module_ctl_get_floatingpoint(_0: number, _1: number): number;
  _openmpt_module_ctl_get_text(_0: number, _1: number): number;
  _openmpt_module_ctl_set(_0: number, _1: number, _2: number): number;
  _openmpt_module_ctl_set_boolean(_0: number, _1: number, _2: number): number;
  _openmpt_module_ctl_set_integer(_0: number, _1: number, _2: number, _3: number): number;
  _openmpt_module_ctl_set_floatingpoint(_0: number, _1: number, _2: number): number;
  _openmpt_module_ctl_set_text(_0: number, _1: number, _2: number): number;
  _openmpt_module_ext_create(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number): number;
  _openmpt_module_ext_create_from_memory(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number, _7: number, _8: number): number;
  _openmpt_module_ext_destroy(_0: number): void;
  _openmpt_module_ext_get_module(_0: number): number;
  _openmpt_module_ext_get_interface(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt9exceptionC2ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number): number;
  __ZNK7openmpt9exception4whatEv(_0: number): number;
  __ZN7openmpt9exceptionD2Ev(_0: number): number;
  _malloc(_0: number): number;
  __ZN7openmpt9exceptionC2ERKS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionC2EOS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionaSERKS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionaSEOS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionD0Ev(_0: number): void;
  __ZN7openmpt24get_supported_extensionsEv(_0: number): void;
  __ZN7openmpt22is_extension_supportedERKNSt3__212basic_stringIcNS0_11char_traitsIcEENS0_9allocatorIcEEEE(_0: number): number;
  __ZN7openmpt23is_extension_supported2ENSt3__217basic_string_viewIcNS0_11char_traitsIcEEEE(_0: number): number;
  __ZN7openmpt22could_open_probabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE(_0: number, _1: number, _2: number): number;
  __ZN7openmpt22could_open_propabilityERNSt3__213basic_istreamIcNS0_11char_traitsIcEEEEdRNS0_13basic_ostreamIcS3_EE(_0: number, _1: number, _2: number): number;
  __ZN7openmpt38probe_file_header_get_recommended_sizeEv(): number;
  __ZN7openmpt17probe_file_headerEyPKSt4bytemy(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): number;
  __ZN7openmpt17probe_file_headerEyPKhmy(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): number;
  __ZN7openmpt17probe_file_headerEyPKSt4bytem(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt17probe_file_headerEyPKhm(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt17probe_file_headerEyRNSt3__213basic_istreamIcNS0_11char_traitsIcEEEE(_0: number, _1: number, _2: number): number;
  __ZN7openmpt6moduleC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC2EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC2EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC2EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleD2Ev(_0: number): number;
  __ZN7openmpt6moduleD0Ev(_0: number): void;
  __ZN7openmpt6module14select_subsongEi(_0: number, _1: number): void;
  __ZNK7openmpt6module20get_selected_subsongEv(_0: number): number;
  __ZN7openmpt6module16set_repeat_countEi(_0: number, _1: number): void;
  __ZNK7openmpt6module16get_repeat_countEv(_0: number): number;
  __ZNK7openmpt6module20get_duration_secondsEv(_0: number): number;
  __ZN7openmpt6module20set_position_secondsEd(_0: number, _1: number): number;
  __ZNK7openmpt6module20get_position_secondsEv(_0: number): number;
  __ZN7openmpt6module22set_position_order_rowEii(_0: number, _1: number, _2: number): number;
  __ZNK7openmpt6module16get_render_paramEi(_0: number, _1: number): number;
  __ZN7openmpt6module16set_render_paramEii(_0: number, _1: number, _2: number): void;
  __ZN7openmpt6module4readEimPs(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6module4readEimPsS1_(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6module4readEimPsS1_S1_S1_(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): number;
  __ZN7openmpt6module4readEimPf(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6module4readEimPfS1_(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6module4readEimPfS1_S1_S1_(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): number;
  __ZN7openmpt6module23read_interleaved_stereoEimPs(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6module21read_interleaved_quadEimPs(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6module23read_interleaved_stereoEimPf(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6module21read_interleaved_quadEimPf(_0: number, _1: number, _2: number, _3: number): number;
  __ZNK7openmpt6module17get_metadata_keysEv(_0: number, _1: number): void;
  __ZNK7openmpt6module12get_metadataERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number, _2: number): void;
  __ZNK7openmpt6module25get_current_estimated_bpmEv(_0: number): number;
  __ZNK7openmpt6module17get_current_speedEv(_0: number): number;
  __ZNK7openmpt6module17get_current_tempoEv(_0: number): number;
  __ZNK7openmpt6module18get_current_tempo2Ev(_0: number): number;
  __ZNK7openmpt6module17get_current_orderEv(_0: number): number;
  __ZNK7openmpt6module19get_current_patternEv(_0: number): number;
  __ZNK7openmpt6module15get_current_rowEv(_0: number): number;
  __ZNK7openmpt6module28get_current_playing_channelsEv(_0: number): number;
  __ZNK7openmpt6module27get_current_channel_vu_monoEi(_0: number, _1: number): number;
  __ZNK7openmpt6module27get_current_channel_vu_leftEi(_0: number, _1: number): number;
  __ZNK7openmpt6module28get_current_channel_vu_rightEi(_0: number, _1: number): number;
  __ZNK7openmpt6module32get_current_channel_vu_rear_leftEi(_0: number, _1: number): number;
  __ZNK7openmpt6module33get_current_channel_vu_rear_rightEi(_0: number, _1: number): number;
  __ZNK7openmpt6module16get_num_subsongsEv(_0: number): number;
  __ZNK7openmpt6module16get_num_channelsEv(_0: number): number;
  __ZNK7openmpt6module14get_num_ordersEv(_0: number): number;
  __ZNK7openmpt6module16get_num_patternsEv(_0: number): number;
  __ZNK7openmpt6module19get_num_instrumentsEv(_0: number): number;
  __ZNK7openmpt6module15get_num_samplesEv(_0: number): number;
  __ZNK7openmpt6module17get_subsong_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module17get_channel_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module15get_order_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module17get_pattern_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module20get_instrument_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module16get_sample_namesEv(_0: number, _1: number): void;
  __ZNK7openmpt6module17get_order_patternEi(_0: number, _1: number): number;
  __ZNK7openmpt6module20get_pattern_num_rowsEi(_0: number, _1: number): number;
  __ZNK7openmpt6module31get_pattern_row_channel_commandEiiii(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZNK7openmpt6module34format_pattern_row_channel_commandEiiii(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNK7openmpt6module37highlight_pattern_row_channel_commandEiiii(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number): void;
  __ZNK7openmpt6module26format_pattern_row_channelEiiimb(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): void;
  __ZNK7openmpt6module29highlight_pattern_row_channelEiiimb(_0: number, _1: number, _2: number, _3: number, _4: number, _5: number, _6: number): void;
  __ZNK7openmpt6module8get_ctlsEv(_0: number, _1: number): void;
  __ZNK7openmpt6module7ctl_getERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number, _2: number): void;
  __ZNK7openmpt6module15ctl_get_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK7openmpt6module15ctl_get_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK7openmpt6module21ctl_get_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number): number;
  __ZNK7openmpt6module12ctl_get_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEE(_0: number, _1: number, _2: number): void;
  __ZN7openmpt6module7ctl_setERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEES9_(_0: number, _1: number, _2: number): void;
  __ZN7openmpt6module15ctl_set_booleanENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEb(_0: number, _1: number, _2: number): void;
  __ZN7openmpt6module15ctl_set_integerENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEx(_0: number, _1: number, _2: number, _3: number): void;
  __ZN7openmpt6module21ctl_set_floatingpointENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEEd(_0: number, _1: number, _2: number): void;
  __ZN7openmpt6module12ctl_set_textENSt3__217basic_string_viewIcNS1_11char_traitsIcEEEES5_(_0: number, _1: number, _2: number): void;
  __ZN7openmpt10module_extC2ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC2ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC2ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC2ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC2EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC2EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC2EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC2EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extD2Ev(_0: number): number;
  __ZN7openmpt10module_extD0Ev(_0: number): void;
  __ZN7openmpt10module_extC2ERKS0_(_0: number, _1: number): number;
  __ZN7openmpt10module_extaSERKS0_(_0: number, _1: number): void;
  __ZN7openmpt10module_ext13get_interfaceERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number): number;
  __ZN7openmpt9exceptionC1ERKNSt3__212basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEE(_0: number, _1: number): number;
  __ZN7openmpt9exceptionC1ERKS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionC1EOS0_(_0: number, _1: number): number;
  __ZN7openmpt9exceptionD1Ev(_0: number): number;
  __ZN7openmpt6moduleC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC1EPKSt4byteS3_RNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC1EPKhS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt6moduleC1EPKcS2_RNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt6moduleD1Ev(_0: number): number;
  __ZN7openmpt10module_extC1ERNSt3__213basic_istreamIcNS1_11char_traitsIcEEEERNS1_13basic_ostreamIcS4_EERKNS1_3mapINS1_12basic_stringIcS4_NS1_9allocatorIcEEEESE_NS1_4lessISE_EENSC_INS1_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC1ERKNSt3__26vectorIhNS1_9allocatorIhEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_NS3_IcEEEESG_NS1_4lessISG_EENS3_INS1_4pairIKSG_SG_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC1ERKNSt3__26vectorIcNS1_9allocatorIcEEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSA_S4_EESF_NS1_4lessISF_EENS3_INS1_4pairIKSF_SF_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC1ERKNSt3__26vectorISt4byteNS1_9allocatorIS3_EEEERNS1_13basic_ostreamIcNS1_11char_traitsIcEEEERKNS1_3mapINS1_12basic_stringIcSB_NS4_IcEEEESH_NS1_4lessISH_EENS4_INS1_4pairIKSH_SH_EEEEEE(_0: number, _1: number, _2: number, _3: number): number;
  __ZN7openmpt10module_extC1EPKhmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC1EPKcmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC1EPKSt4bytemRNSt3__213basic_ostreamIcNS4_11char_traitsIcEEEERKNS4_3mapINS4_12basic_stringIcS7_NS4_9allocatorIcEEEESE_NS4_4lessISE_EENSC_INS4_4pairIKSE_SE_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extC1EPKvmRNSt3__213basic_ostreamIcNS3_11char_traitsIcEEEERKNS3_3mapINS3_12basic_stringIcS6_NS3_9allocatorIcEEEESD_NS3_4lessISD_EENSB_INS3_4pairIKSD_SD_EEEEEE(_0: number, _1: number, _2: number, _3: number, _4: number): number;
  __ZN7openmpt10module_extD1Ev(_0: number): number;
  __ZN7openmpt10module_extC1ERKS0_(_0: number, _1: number): number;
}

interface EmbindModule {
}
export type MainModule = WasmModule & EmbindModule & EmscriptenModule & { UTF8ToString: typeof window['UTF8ToString'] };
